version: '3.8'

services:
  postgres:
    container_name: "ququiz-postgres"
    image: 'postgres:alpine3.20'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - ./.env
    networks:
      - ququiz
  authentications:
    container_name: "ququiz-authentications"
    image: 'alexadamm/ququiz-auth:v1.0'
    ports:
      - 3501:3000
      - 4501:4000
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./protos:/app/src
    depends_on:
      - postgres
    networks:
      - ququiz
  mongodb:
    container_name: 'ququiz-mongo'
    image: 'mongo:8.0.0-rc6'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    env_file:
      - ./.env
    networks:
      - ququiz
  dkron:
    container_name: ququiz-dkron
    image: dkron/dkron
    ports:
      - '9911:8080'
    command: agent --server --bootstrap-expect=1 --node-name=node1
    environment:
      - DKRON_BACKEND_MACHINE_URL=dkron://dkron:8946
    restart: always
    networks:
      - ququiz
  quiz:
    container_name: "ququiz-quiz"
    image: lintangbirdas/quiz-command-service:v1
    ports:
      - 3502:3000
    env_file:
      - ./.env
   
    depends_on:
      - authentications
      - dkron
      - mongodb
    networks:
      - ququiz
  
  redis:
    image: redis:7.0.1-alpine3.16
    container_name: redis
    hostname: redis
    restart: always
    mem_limit: "2000mb"
    cpus: 2
    ports:
      - 6379:6379
    networks:
      - ququiz

  quiz-query-service:
    image: lintangbirdas/quiz-query-service:v1 
    container_name: quiz-query-service
    restart: always
    mem_limit: "2000mb"
    cpus: 2
    ports: 
      - 3503:3503
      - 6005:6005
    networks:
      - ququiz
    
networks:
  ququiz:

