version: '3.8'

services:
  postgres:
    container_name: "ququiz-postgres"
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - ./.env
    networks:
      - ququiz
  authentications:
    container_name: "ququiz-authentications"
    image: 'alexadamm/ququiz-auth:v1.0'
    ports:
      - 3501:3000
      - 4501:4000
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./protos:/app/src
    depends_on:
      - postgres
    networks:
      - ququiz
networks:
  ququiz:

